spring.application.name=incident-management-service
server.port=${PORT:8080}

# MySQL datasource configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
